- name: Playbook for Releasing App  Servers
  hosts: localhost
  serial: 1
  gather_facts: no
  become: true
  vars_files:
    - ../group_vars/all
  roles:
    - ../../roles/apt
    - ../../roles/pip-install
    - ../../roles/copy
    - ../../roles/service
